managed_nodes:
  hosts:
    node1:
      ansible_host: 192.168.56.71
      ansible_user: vagrant
      ansible_ssh_pass: ansible
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
    node2:
      ansible_host: 192.168.56.72
      ansible_user: vagrant
      ansible_ssh_pass: ansible
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_rsa
