#name: Merge Release Into Main

#on:
#  push:
#    branches:
#      - 'release/*'

#jobs:
#  main:
#    name: Main PR
#    runs-on: ubuntu-latest
#    steps:
#      # Linting step is the first step.
#      - name: Lint Workflow
#        run: |
#          # Lint workflow file.
#          npm install -g remark-cli remark-lint
#          remark -f -i .github/workflows/*.yml

#      - name: git checkout
#        uses: actions/checkout@v3
#        with:
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

#      # If successful proceed with PR creation.
#      - name: Create PR
#        id: open-pr
#        uses: repo-sync/pull-request@v2
#        with:
#          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          destination_branch: ${{ github.event.repository.default_branch }}
#          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
#          pr_body: "Automated Pull Request"
#          pr_reviewer: "jonathan.marshall"
#          pr_assignee: "jonathan.marshall"

#      - name: Enable Automerge
#        if: steps.open-pr.outputs.pr_number != ''
#        uses: peter-evans/enable-pull-request-automerge@v2
#        with:
#          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
#          merge-method: merge

#      - name: Create Tag
#        if: success()
#        run: git tag -a v1.0 -m "Release version 1.0"

#      - name: Push Tag
#        if: success()
#        run: git push origin v1.0
